void start(void);
void command(char);
void data(char);
void sendString(char *StringOfCharacters);
void cut(char *str);
void sendInteger(int x);
void setCursor(int row,int column);
void clearScreen(void);
void home(void);
void cursor(void);
void noCursor(void);
void blink(void);
void noBlink(void);
void display(void);
void noDisplay(void);
void scrollDisplayLeft(void);
void scrollDisplayRight(void);
void autoscroll(void);
void noAutoscroll(void);
void createChar(int num,unsigned int *charArray);